name: build-docker-image

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
      - name: Copy file
        run: | 
            cp ruoyi-starter/ruoyi-admin/target/ruoyi-admin.jar docker/admin
            cp ruoyi-starter/ruoyi-api/target/ruoyi-api.jar docker/api
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Admin push
        uses: docker/build-push-action@v3
        with:
          context: docker/admin/
          push: true
          #指定用户/仓库名
          tags: thetbw/shop-admin:latest
      - name: Build Api push
        uses: docker/build-push-action@v3
        with:
          context: docker/api/
          push: true
          #指定用户/仓库名
          tags: thetbw/shop-api:latest
              
